### ISSUE TITLE
How to add a link to a UILabel?

### ISSUE THREAD

**Issue by andrewhavens** [skellock/motion-mastr#1]
I am trying to add a link to a UILabel, but can't figure out what I am missing. Here's my RMQ method:

```
def my_label(st)
  st.frame = {l: 0, t: 0, w: 300, h: 18, centered: :horizontal}
  st.attributed_text = mastr("Click on ").add("this", link: "http://google.com").build
end
```

What am I missing to make the link tappable?

**Comment by skellock** [comment]
I'm not sure it's possible.  I know it's possible with UILabel.  It is with UITextView though.  There's a protocol called UITextViewDelegate that allows `textView:shouldInteractWithURL:inRange:` for you to capture those clicks.

Heads up though.  That doesn't actually work in the simulator.  I think that's a bug in the simulator though.

**Comment by andrewhavens** [comment]
Thanks, that helped. I figured out what I was missing based on [the docs for that delegate method](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/UITextViewDelegate/textView:shouldInteractWithURL:inRange:):

> ... Implementation of this method is optional. By default, the text view opens the application responsible for handling the URL type and passes it the URL. ...
> 
> IMPORTANT
> Links in text views are interactive only if the text view is selectable but noneditable. That is, if the value of the UITextView selectable property is YES and the isEditable property is NO.

So I didn't need to implement the method, but I had to set those properties:

``` ruby
def my_label(st)
  st.frame = {l: 0, t: 0, w: 300, h: 18, centered: :horizontal}
  st.attributed_text = mastr("Click on ").add("this", link: "http://google.com").build
  st.editable = false # I think this is the default
  st.selectable = true
end
```

**Comment by andrewhavens** [comment]
@skellock Do you know how I can change the color of the link? It seems the usual methods do not work:

```
mastr("Click on ").add("this", link: "http://google.com", color: color.white).build
# blue link
mastr("Click on ").add("this", link: "http://google.com", foreground_color: color.white).build
# blue link
```

**Comment by andrewhavens** [comment]
Figured it out, though it seems a little strange. I had to set some (but not all) defaults on the text view:

```
def my_text_view(st)
  st.frame = {t: 0, w: 300, h: 18, centered: :horizontal}
  st.editable = false # I think this is the default
  st.selectable = true
  st.attributed_text = mastr("Click on ").add("this", link: "http://google.com", font: font.bold, underline_style: :style_single).build
  st.view.linkTextAttributes = {
    NSForegroundColorAttributeName => color.white,
    # not these:
    # NSFontAttributeName => font.bold_tiny,
    # NSUnderlineColorAttributeName => color.white,
    # NSUnderlineStyleAttributeName => NSUnderlinePatternSolid
  }
end
```

**Comment by skellock** [comment]
Ya.  Unfortunately that's out the API works.  You have to set the linkTextAttributes separately.
