### ISSUE TITLE
coloring links

### ISSUE THREAD

**Issue by dam13n** [skellock/motion-mastr#2]
I can't seem to get link coloring to work.

I also had to pass in NSURLs for the link property. Strings didn't work.

**Comment by skellock** [comment]
Apple has a different API for links and colourizing.  It's strange.

Check it out:

https://github.com/skellock/motion-mastr/issues/1

**Comment by dam13n** [comment]
ah myyy bad. i saw the 1 issue too, and was like..."nah, likely not the same thing." thanks!
